db:
  development:
    adapter: sqlite3
    database: db/blamethrower.db
  production:
    adapter: sqlite3
    database: db/blamethrower.db
mail:
  smtp:
    host: mail.fifthroomcreative.com
    port: 587
    user: mike@fifthroomcreative.com
    pass: mikegreen
    auth: plain
  welcome_message_template: |
    Hello, <%= name %>
    Welcome to BlameThrower!
  
    Your Username: <%= name %>
    Your Email: <%= email %>
    Your Password: <%= pass %>
  
    Please keep this information in case you forget your login or password.
  
    Happy blaming,
    The BlameThrower Team
  forgot_password_template: |
    Hello, <%= name %>
    We value your privacy, so much that we irreversibly encrypt your password once you sign up.
    While we're unable to tell you your old password, we did give you a new one.
    
    Try logging in to BlameThrower with the information below.
    Username: <%= name %>
    Password: <%= new_pass %>
    
    Thanks,
    The BlameThrower Team