database:
  development:
    adapter: "sqlite"
    database: "/Users/mike/Development/Projects/blamethrower/db/blamethrower.db"
  production:
    adapter: "sqlite"
    database: "/Users/mike/Development/Projects/blamethrower/db/blamethrower.db"